install: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - cmake -DBUILD=all -G "Visual Studio 11 2012 Win64" .

build_script:
  - msbuild /m MP.sln
  - msbuild RUN_TESTS.vcxproj
