language: c++

os:
  - linux

env:
  global:
    - secure: |-
        QFQl9tcXV3RZ8G0mkZF71l6v1PrU8qE1B6mu7Y5agsgx0WqhoWyWXQgRzduPtPBsYzk8oO
        n/BtdN5d2YW9G0ewcKv1CB5OnoFWfXxy+0vkjjgH3odUQZr41vJ72elcLzVXwvSitzIeta
        six7w64OcBxbMU87P5sqnO6nw70elG0=
  matrix:
    - BUILD=doc
    - BUILD=native
    - BUILD=cross

matrix:
  include:
    - os: osx
      env: BUILD=native

script:
  - support/travis-build.py
