language: c++

# Use the container-based infrastructure.
sudo: false

cache: ccache

matrix:
  include:
    - os: linux
      env: BUILD=doc
      addons: {apt: {packages: [python-virtualenv]}}
    - os: linux
      env: BUILD=native
      addons: {apt: {packages: [unixodbc-dev]}}
    - os: osx
      osx_image: xcode7.3
      env: BUILD=native

script:
  - support/travis-build.py
