# Set language to "java" to make sure that JRE is installed.
language: java

os:
  - linux
  - osx

env:
  - BUILD=native
  - BUILD=cross

matrix:
  exclude:
    - os: osx
      env: BUILD=cross

script:
  - support/travis-build.py
