language: c++

os:
  - linux

env:
  - BUILD=native
  - BUILD=cross

matrix:
  include:
    - os: linux
      env: BUILD=doc
    - os: osx
      env: BUILD=native

script:
  - support/travis-build.py
