language: c++

os:
  - linux

env:
  global:
    - secure: |-
        TUZKaV/W4ldNNY5UqPqUgVGL3oMnktX2ny9c/FCa1tdFU34XBkMtDFIIQ19Qu/GGIYbG32
        Pdf/rX5+65kmjONSusBheRlVlWfZ2/cXjGFFFSkNn2JLLyGWpEZ6fdvr9yQVD57TXsY9Zf
        allEyZLeSLeWFPeuhEOxq4F8YhKlQxI=
  matrix:
    - BUILD=native
    - BUILD=cross
    - BUILD=doc

matrix:
  include:
    - os: osx
      env: BUILD=native

script:
  - support/travis-build.py
